CREATE TABLE IF NOT EXISTS lobby_players(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	lobby_id INTEGER,
	user1_id INTEGER,
	user2_id INTEGER,
	is_ready BOOLEAN DEFAULT FALSE,
	joined_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (lobby_id) REFERENCES lobbies(id),
	FOREIGN KEY (user1_id) REFERENCES users(id),
	FOREIGN KEY (user2_id) REFERENCES users(id)
);
