CREATE TABLE gamePlayer (
    gameId TEXT NOT NULL,
    userId INTEGER NOT NULL,
    FOREIGN KEY (gameId) REFERENCES games(gameId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (gameId, userId)
);
